[package]
name = "nbalive"
version = "0.1.0"
authors = ["suchin"]

[dependencies]
rustc-serialize = "0.3"
regex = "0.1.69"
lazy_static = "0.2.1"
hyper="*"
serde_json = "*"
itertools = "*"
[dependencies.url]
url = "https://github.com/servo/rust-url"
